name: Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        name: Install packages
        run: yarn install

      - name: Check previous build existence
        id: check_build_existence
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"

      - if: steps.check_build_existence.outputs.files_exists == 'true'
        name: Clean build
        run: rm -rf build

      - name: Build
        run: yarn build

  eslint:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        name: Install packages
        run: yarn install

      - name: Check violation of linter rules
        run: yarn lint

  build-storybook:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        name: Install packages
        run: yarn install

      - name: Check previous storybook build existence
        id: check_storybook_build_existence
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"

      - if: steps.check_storybook_build_existence.outputs.files_exists == 'true'
        name: Clean storybook build
        run: rm -rf storybook-static

      - name: Build Storybook
        run: yarn build-storybook